#!/usr/bin/env bash
# configure SSH client to connect to server without typing a password

Host server1
    HostName 34.224.15.191
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
